# Generated by Django 2.1 on 2021-07-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghetto', '0002_auto_20210723_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='hospitalhelpline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='occupants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='policehelpline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
