# Generated by Django 2.1 on 2021-07-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghetto', '0004_auto_20210723_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='posttitle',
        ),
    ]
