# Generated by Django 2.1 on 2021-07-23 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ghetto', '0005_auto_20210723_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Postii',
        ),
    ]
