# Generated by Django 2.1 on 2021-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghetto', '0008_auto_20210724_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(blank=True, to='ghetto.Category'),
        ),
    ]
